### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by janpieper** [gmtprime/yggdrasil#1]
If I try to use the first example from the README:

``` elixir
Yggdrasil.Feed.subscribe Yggdrasil.Feed,
  Yggdrasil.Broker.Redis,
  "trees",
  &(IO.puts "#{inspect &1}")
```

I get this error:

```
** (exit) exited in: GenServer.call(Yggdrasil.Feed, {:subscribe, Yggdrasil.Broker.Redis, "trees"}, 5000)
    ** (EXIT) no process
    (elixir) lib/gen_server.ex:596: GenServer.call/3
             lib/yggdrasil/feed.ex:32: Yggdrasil.Feed.subscribe/4
```

Can you please add some more information to the README, how to use this library? The examples look quite useful, but I can't get them working.

Installed Elxir:

```
$ elixir --version
Erlang/OTP 19 [erts-8.0.2] [source-9503fff] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.3.2
```

**Comment by alexdesousa** [comment]
Hello! Thank you very much for the feedback.

Right now I'm finishing the new version, so I don't recommend using `Yggdrasil` just yet. The current version lacks some stuff I've been developing in the past week. For example, `:phoenix_pubsub` integration to send the events, instead of using `GenEvent`. Also, I'm improving compatibility with Erlang 19 and Elixir 1.3 and simplify the API.

I think I'll have the new version with documentation and examples at the end of this week. If you want to try the new version, it's in the experimental branch. But it doesn't have documentation yet. Hopefully, tomorrow I'll finish the documentation for the experimental branch.

**Comment by alexdesousa** [comment]
@janpieper I've just uploaded the new version if you want to check it out.
