### ISSUE TITLE
Awesome project!

### ISSUE THREAD

**Issue by BlueHotDog** [gmtprime/yggdrasil#4]
Hi! 
Very very very awesome project!
One missing piece of functionality(that i can open a PR for assuming it makes sense) - How can i send rabbitmq options(the 5th param to AMQP.Basic.publish) - that can include headers etc..
Maybe a general options param to publish can be added that each adapter can do whatever he wants with?
Maybe the message encoder can do more and extract headers?
What do you think

**Comment by alexdesousa** [comment]
@BlueHotDog Sorry, for the delay and thanks for the suggestion. I think the change you propose does make sense. It could be done in several ways, but I think is enough to re-route the `options` from `Yggdrasil.publish/2` to `AMQP.Basic.publish/5`. It would be a matter of changing `Yggdrasil.publish/2` to `Yggdrasil.publish/3` and modify every adapter to accept an addional `options` argument. By default, this argument would be an empty `Keyword` list.

**Comment by alexdesousa** [comment]
The latest version of `Yggdrasil` has this feature.

For example, when using [RabbitMQ Delayed Message Exchange plugin](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange), it is possible to delay the messages published in an exchange. This exchanges have a special name (`x-delayed-message`) and they must be created with an `x-delay-type` e.g `topic`, `direct`, etc. (`Yggdrasil`, only supports exchanges of type `topic`).

Supposing we have the exchange `custom.delayed` of type `x-delayed-message` and `x-delay-type` `topic`, this would be the way to delay publishing a message 60 seconds:
```
iex> alias Yggdrasil.Channel
iex> chan = %Channel{adapter: :rabbitmq, name: {"custom.delayed", "test"}}
iex> Yggdrasil.subscribe(chan)
iex> flush()
{:Y_CONNECTED,
 %Yggdrasil.Channel{adapter: Yggdrasil.Subscriber.Adapter.RabbitMQ,
  name: {"custom.delayed", "test"}, namespace: Yggdrasil,
  transformer: Yggdrasil.Transformer.Default}}
iex> options = [headers: [{"x-delay", :long, 60_000}]]
iex> Yggdrasil.publish(chan, "my delayed message", options)
```
after 60 seconds, the message should be in `iex` mailbox:

```
iex> flush()
{:Y_EVENT,
 %Yggdrasil.Channel{adapter: Yggdrasil.Subscriber.Adapter.RabbitMQ,
  name: {"custom.delayed", "test"}, namespace: Yggdrasil,
  transformer: Yggdrasil.Transformer.Default}, "my delayed message"}
```
This update does not brake the previous version because the `options` argument is optional.
